services:
  caddy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deploy/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  db:
    env_file:
      - .env.dev
    restart: unless-stopped

  api:
    env_file:
      - .env.dev
    restart: unless-stopped

  web:
    env_file:
      - .env.dev
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
